"""initial schema

Revision ID: 2262ba9d6dc8
Revises: 
Create Date: 2026-09-07 14:31:36.658821
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2262ba9d6dc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('sector', sa.String(length=40), nullable=False),
    sa.Column('demand', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_careers_demand'), ['demand'], unique=False)
        batch_op.create_index(batch_op.f('ix_careers_sector'), ['sector'], unique=False)

    op.create_table('courses',
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_type', sa.String(length=10), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_provider'), ['provider'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('top_career_id', sa.String(length=64), nullable=False),
    sa.Column('top_sector', sa.String(length=40), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_runs_top_career_id'), ['top_career_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_runs_top_sector'), ['top_sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_runs_user_id'), ['user_id'], unique=False)

    op.create_table('saved_careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'career_id', name='uq_saved_career')
    )
    with op.batch_alter_table('saved_careers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_careers_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('emirate', sa.String(length=40), nullable=True),
    sa.Column('school', sa.String(length=160), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('track', sa.String(length=20), nullable=True),
    sa.Column('grades', sa.JSON(), nullable=False),
    sa.Column('emsat', sa.JSON(), nullable=False),
    sa.Column('riasec_answers', sa.JSON(), nullable=False),
    sa.Column('bigfive_answers', sa.JSON(), nullable=False),
    sa.Column('riasec', sa.JSON(), nullable=False),
    sa.Column('bigfive', sa.JSON(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('saved_careers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_careers_user_id'))

    op.drop_table('saved_careers')
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_top_sector'))
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_top_career_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_created_at'))

    op.drop_table('recommendation_runs')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_provider'))
        batch_op.drop_index(batch_op.f('ix_courses_level'))
        batch_op.drop_index(batch_op.f('ix_courses_language'))
        batch_op.drop_index(batch_op.f('ix_courses_cost'))

    op.drop_table('courses')
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_careers_sector'))
        batch_op.drop_index(batch_op.f('ix_careers_demand'))

    op.drop_table('careers')
    # ### end Alembic commands ###
